name: todo
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: "3.7.2"
  flutter: "3.29.3"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get_storage: ^2.1.1
  get: ^4.7.2
  flutter_local_notifications: ^19.2.1
  flutter_native_timezone: ^2.0.0
  intl: ^0.20.2
  google_fonts: ^6.2.1
  date_picker_timeline: ^1.2.6
  sqflite: ^2.4.2
  flutter_staggered_animations: ^1.1.1
  flutter_svg: ^2.1.0
  rxdart: ^0.28.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0

dependency_overrides:
  intl: ^0.20.2

flutter_icons:
  android: true
  ios: true
  image_path: "images/appicon.jpeg"

flutter:
  uses-material-design: true

  assets:
    - images/person.jpeg
    - images/task.svg
